# Gathering MassDOT Data for Somerville Crashes

In [2]:
%pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.67.0-cp314-cp314-win_amd64.whl.metadata (139 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in .\.venv\Lib\site-packages (from matplotlib) (2.5.3)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-13.0.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: python-dateutil>=2.7 in .\.venv\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ----------------- ---------------------- 4.2/9.5 MB 24.3 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 25.9 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 23.6 MB/s  0:00:00
Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl (240 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.67.0-cp314-cp314-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 2.5/2.5 MB 26.0 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl (72 kB)
Downloading pillow-13.0.0-cp314-cp314-win_amd64.whl (7.3 MB)
   ---------------------------------------- 0.0/7.3 MB ? eta -:--:--
   ------------------------------ --------- 5.5/7.3 MB 26.9 MB/s eta 0:00:01
   ---------------------------------------- 7.3/7.3 MB 25.8 MB/s  0:00:00
Downloading pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------- ----------------- 4/7 [cycler]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.67.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-13.0.0 pyparsing-3.3.3
Note: you may need to restart the kernel to use updated packages.

In [4]:
from IPython.display import display
import matplotlib.pyplot as plt
import requests
import pandas as pd
import numpy as np


all_features = []


base_url = f"https://gis.crashdata.dot.mass.gov/arcgis/rest/services/MassDOT/MASSDOT_ODP_OPEN_2025/FeatureServer/0/query"
    
params = {
    "where": " CITY_TOWN_NAME = 'CAMBRIDGE' ",
    "outFields": "*",
    "outSR": "4326",
    "f": "json",
    "returnGeometry": "true",
    "resultOffset": 0,
    "resultRecordCount": 2000
    }

while True:
        
    response = requests.get(base_url, params=params)
    data = response.json()
    features = data.get("features", [])
        
    if not features:
        break
        
    all_features.extend(features)
    params["resultOffset"] += params["resultRecordCount"]

records = [f["attributes"] for f in all_features]

massdot_df = pd.DataFrame(records)
print("Shape:", massdot_df.shape)
pd.set_option('display.max_columns', None)
massdot_df.head()

Shape: (1389, 124)

,CRASH_NUMB,CITY_TOWN_NAME,CRASH_DATE_TEXT,CRASH_TIME_2,CRASH_DATETIME,CRASH_HOUR,CRASH_STATUS,CRASH_SEVERITY_DESCR,MAX_INJR_SVRTY_CL,NUMB_VEHC,NUMB_NONFATAL_INJR,NUMB_FATAL_INJR,POLC_AGNCY_TYPE_DESCR,MANR_COLL_DESCR,VEHC_MNVR_ACTN_CL,VEHC_TRVL_DIRC_CL,VEHC_SEQ_EVENTS_CL,AMBNT_LIGHT_DESCR,WEATH_COND_DESCR,ROAD_SURF_COND_DESCR,FIRST_HRMF_EVENT_DESCR,MOST_HRMFL_EVT_CL,DRVR_CNTRB_CIRC_CL,VEHC_CONFIG_CL,STREET_NUMB,RDWY,DIST_DIRC_FROM_INT,NEAR_INT_RDWY,MM_RTE,DIST_DIRC_MILEMARKER,MILEMARKER,EXIT_RTE,DIST_DIRC_EXIT,EXIT_NUMB,DIST_DIRC_LANDMARK,LANDMARK,RDWY_JNCT_TYPE_DESCR,TRAF_CNTRL_DEVC_TYPE_DESCR,TRAFY_DESCR_DESCR,JURISDICTN,FIRST_HRMF_EVENT_LOC_DESCR,NON_MTRST_TYPE_CL,NON_MTRST_ACTN_CL,NON_MTRST_LOC_CL,IS_GEOCODED,GEOCODING_METHOD_NAME,X,Y,LAT,LON,RMV_DOC_IDS,CRASH_RPT_IDS,YEAR,AGE_DRVR_YNGST,AGE_DRVR_OLDEST,AGE_NONMTRST_YNGST,AGE_NONMTRST_OLDEST,DRVR_DISTRACTED_CL,DISTRICT_NUM,RPA_ABBR,VEHC_EMER_USE_CL,VEHC_TOWED_FROM_SCENE_CL,CNTY_NAME,FMCSA_RPTBL_CL,FMCSA_RPTBL,HIT_RUN_DESCR,LCLTY_NAME,ROAD_CNTRB_DESCR,SCHL_BUS_RELD_DESCR,SPEED_LIMIT,TRAF_CNTRL_DEVC_FUNC_DESCR,WORK_ZONE_RELD_DESCR,AADT,AADT_YEAR,PK_PCT_SUT,AV_PCT_SUT,PK_PCT_CT,AV_PCT_CT,CURB,TRUCK_RTE,LT_SIDEWLK,RT_SIDEWLK,SHLDR_LT_W,SHLDR_LT_T,SURFACE_WD,SURFACE_TP,SHLDR_RT_W,SHLDR_RT_T,NUM_LANES,OPP_LANES,MED_WIDTH,MED_TYPE,URBAN_TYPE,F_CLASS,URBAN_AREA,FD_AID_RTE,FACILITY,OPERATION,CONTROL,PEAK_LANE,SPEED_LIM,STREETNAME,FROMSTREETNAME,TOSTREETNAME,CITY,STRUCT_CND,TERRAIN,URBAN_LOC_TYPE,AADT_DERIV,STATN_NUM,OP_DIR_SL,SHLDR_UL_T,SHLDR_UL_W,T_EXC_TYPE,T_EXC_TIME,F_F_CLASS,OBJECTID,TRAFFIC_CONTROL_TYPE_DESCR,NON_MTRST_ORIGIN_DEST_CL,NON_MTRST_CNTRB_CIRC_CL,NON_MTRST_DISTRACTED_BY_CL,NON_MTRST_ALC_SUSPD_TYPE_CL,NON_MTRST_DRUG_SUSPD_TYPE_CL,NON_MTRST_EVENT_SEQ_CL
0,5481663,CAMBRIDGE,01 04 2025,1:40 PM,1735998000000,01:00PM to 01:59PM,Open,Property damage only (none injured),No Apparent Injury (O),1,0,0,Local police,Angle,V1: Turning left,V1: S,V1:(Collision with cyclist),Daylight,Clear,Dry,Collision with cyclist,"V1:(Collision with cyclist (bicycle, tricycle,...","D1: (Failed to yield right of way),(No imprope...",V1:(Passenger car),49,WHITE STREET Rte N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not at junction,No controls,"Two-way, not divided",City or Town accepted road,Outside roadway,VU2: Bicyclist,"VU2: Walking, running or cycling",VU2: Not in roadway,Yes,At Address,231476.344647,904374.851709,42.389248,-71.117733,PW20254517408,25000014,2025,65-74,65-74,25-34,25-34,NaN,6,MAPC,V1:(No),V1:(No),MIDDLESEX,"V1:(No, not federally reportable)","No, not federally reportable",No hit and run,None,None,"No, school bus not involved",25.0,Not reported,No,1154,NaN,NaN,NaN,NaN,NaN,Both sides,NaN,6,6,0,No Shoulder,22,Surface-treated road,0,No Shoulder,2,0,0,None,Large Urbanized Area,Local,Boston (MA-NH-RI),None,Mainline roadway,One-way traffic,No Access Control,NaN,NaN,WHITE STREET,SOMERVILLE CITY LINE,SOMERVILLE AVENUE,CAMBRIDGE,Fair,Level Terrain,None,NaN,NaN,NaN,0,0,NaN,NaN,Local,5151794,VU2: None,NaN,,,NaN,NaN,
1,5481658,CAMBRIDGE,01 04 2025,10:26 AM,1735986360000,10:00AM to 10:59AM,Open,Property damage only (none injured),No Apparent Injury (O),1,0,0,Local police,Unknown,V1: Parked,V1: U,V1:(Collision with parked motor vehicle),Unknown,Unknown,Unknown,Collision with parked motor vehicle,V1:(Collision with parked motor vehicle),D1: (No improper driving),V1:(Passenger car),1462,CAMBRIDGE ST Rte W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not at junction,No controls,"Two-way, divided, unprotected median",City or Town accepted road,Roadway,NaN,NaN,NaN,Yes,At Address,232678.648077,902691.137933,42.374040,-71.103226,PW20254517407,25000013,2025,65-74,65-74,NaN,NaN,D1: Not Distracted,6,MAPC,V1:(No),V1:(No),MIDDLESEX,"V1:(No, not federally reportable)","No, not federally reportable","Yes, hit and run",None,Unknown,"No, school bus not involved",25.0,"No, device not functioning",No,15879,2020,0.477,779,0.068,95,Both sides,NaN,10,10,0,No Shoulder,50,Bituminous concrete road,0,No Shoulder,2,0,0,None,Large Urbanized Area,Urban minor arterial or rural major collector,Boston (MA-NH-RI),None,Mainline roadway,Two-way traffic,No Access Control,NaN,99,CAMBRIDGE STREET,MONSIGNOR OBRIEN HIGHWAY,MASSACHUSETTS AVENUE,CAMBRIDGE,Fair,Level Terrain,None,Grown from Prior Year HPMS Network,NaN,99,0,0,NaN,NaN,Minor Arterial,5151799,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5481657,CAMBRIDGE,01 02 2025,4:30 PM,1735835400000,04:00PM to 04:59PM,Open,Property damage only (none injured),No Apparent Injury (O),2,0,0,Local police,"Sideswipe, same direction",V1: Travelling straight ahead / V2: Parked,V1: S / V2:,V1:(Collision with parked motor vehicle) V2:(...,Daylight,Clear,Dry,Collision with parked motor vehicle,V1:(Collision with parked motor vehicle) / V2:...,D1: (Unknown),V1:(Passenger car) / V2:(Passenger car),269,VASSAR STREET Rte S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not at junction,No controls,"Two-way, divided, unprotected median",City or Town accepted road,Roadway,NaN,NaN,NaN,Yes,At Address,232712.530993,900703.721835,42.356147,-71.102927,PW20254517396,25000007,2025,25-34,25-34,NaN,NaN,NaN,6,MAPC,V1:(No) / V2:(No),V1:(No) / V2:(No),MIDDLESEX,"V1:(No, not federally reportable) / V2:(No, no...","No, not federally reportable",No hit and run,None,None,"No, school bus not involved",25.0,Not reported,No,7660,2020,0.232,376,0,45,Both sides,NaN,8,8,0,No Shoulder,40,Surface-treated road,0,No Shoulder,2,0,0,None,Large Urbanized Area,Urban minor arterial or rural major collector,Boston (MA-NH-RI),None,Mainline roadway,Two-way traffic,No Access Control,NaN,99,VASSAR STREET,MAIN STREET,MEMORIAL DRIVE,CAMBRIDGE,Fair,Level Terrain,None,Grown from Prior Year HPMS Network,NaN,99,0,0,NaN,NaN,Minor Arterial,5151800,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5481656,CAMBRIDGE,01 02 2025,9:26 AM,1735809960000,09:00AM to 09:59AM,Open,Property damage only (none injured),No Apparent Injury (O),2,0,0,Local police,Angle,V1: Turning left / V2: Travelling straight ahead,V1: N / V2: E,V1:(Collision with motor vehicle in traffic) ...,Daylight,Clear,Dry,Collision with motor vehicle in traffic,V1:(Collision with motor vehicle in traffic) /...,D1: (Glare) / D2: (Unknown),"V1:(Single-unit truck (2-axle, 6-tires)) / V2:...",NaN,HANCOCK STREET Rte N / BROADWAY Rte E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T-intersection,Stop signs,"Two-way, not divided",City or Town accepted road,Roadway,NaN,NaN,NaN,Yes,At Intersection,232446.546900,902387.374800,42.371315,-71.106062,PW20254517392,25000004,2025,35-44,55-64,NaN,NaN,D1: Not Distracted,6,MAPC,V1:(No) / V2:(No),V1:(No) / V2:(No),MIDDLESEX,"V1:(No, not federally reportable) / V2:(No, no...","No, not federally reportable",No hit and run,None,Unknown,"No, school bus not involved",25.0,"Yes, device functioning",No,1154,NaN,NaN,NaN,NaN,NaN,Both sides,Not a parkway - not on a designated truck route,6,6,0,No Shoulder,26,Surface-treated road,0,No Shoulder,2,0,0,None,Large Urbanized Area,Local,Boston (MA-NH-RI),None,Mainline roadway,One-way traffic,No Access Control,NaN,NaN,HANCOCK STREET,KINNAIRD STREET,BROADWAY,CAMBRIDGE,Fair,Level Terrain,None,NaN,NaN,NaN,0,0,Cambridge Overnight Exclusions,"11PM to 6AM, 7 Days",Local,5151801,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5481633,CAMBRIDGE,01 03 2025,4:50 PM,1735923000000,04:00PM to 04:59PM,Open,Unknown,Not reported,2,0,0,Local police,Unknown,V1: Unknown / V2: Parked,V1: U / V2:,V1:(Collision with parked motor vehicle),Dark - lighted roadway,Clear,Unknown,Collision with parked motor vehicle,V1:(Unknown) / V2:(Unknown),NaN,V1:(Other) / V2:(Passenger car),748,MEMORIAL DRIVE Rte 6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Driveway,No controls,Unknown,Department of Conservation and Recreation,Unknown,NaN,NaN,NaN,Yes,At Address,231683.551337,900911.210561,42.358057,-71.115406,PW20254517403,25000011,2025,NaN,NaN,NaN,NaN,NaN,6,MAPC,V1:(No) / V2:(No),V1:(No) / V2:(No),MIDDLESEX,"V1:(No, not federally reportable) / V2:(No, no...","No, not federally reportable","Yes, hit and run",None,Unknown,"No, school bus not involved",25.0,Not reported,No,15826,2020,0.558,728,0.155,174,Both sides,NaN,6,6,0,No Shoulder,40,Bituminous concrete road,0,No Shoulder,4,0,0,None,Large Urbanized Area,Rural or urban principal arterial,Boston (MA-NH-RI),None,Mainline roadway,Two-way traffic,Partial Access Control,NaN,35,MEMORIAL DRIVE,FRESH POND PARKWAY,RAMP-RT 2 TO RTS 3 NB/2 WB (MEM DR),CAMBRIDGE,Fair,Level Terrain,None,Pulled back from HPMS network estimation routine,NaN,35,0,0,NaN,NaN,Principal Arterial - Other,5151824,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
massdot_df["date"] = pd.to_datetime(massdot_df["CRASH_DATE_TEXT"], format="%m %d %Y").dt.date
massdot_df["time"] = pd.to_datetime(massdot_df["CRASH_TIME_2"], format="%I:%M %p").dt.strftime("%H:%M:%S")
massdot_df["injuryseverity"] = np.select(
    [pd.to_numeric(massdot_df["NUMB_FATAL_INJR"], errors="coerce").fillna(0) > 0,
    pd.to_numeric(massdot_df["NUMB_NONFATAL_INJR"], errors="coerce").fillna(0) > 0
    ],
    [2, 1],
    default=0
)

nm = massdot_df["NON_MTRST_TYPE_CL"].fillna("").str.lower()
massdot_df["cyclists_involved"] = nm.str.count("bicyclist")
massdot_df["pedestrians_involved"] = nm.str.count("pedestrian")

massdot_df["source"] = "MassDOT"
massdot_df["id"] = massdot_df["CRASH_NUMB"]

def clean_street(s):
    return (s.astype("string").str.strip()
             .str.replace(r"\s+Rte\s*\S*", "", regex=True)   
             .str.replace(r"\s+/\s+", " & ", regex=True))

num = (pd.to_numeric(massdot_df["STREET_NUMB"], errors="coerce")
         .astype("Int64").astype("string"))
rdwy = clean_street(massdot_df["RDWY"])
near = clean_street(massdot_df["NEAR_INT_RDWY"])
massdot_df["police"] = (massdot_df["POLC_AGNCY_TYPE_DESCR"].str.strip()
                  .replace({"Local police": "Local", "State police": "State"}))
addr = rdwy.copy()
addr = addr.mask(near.notna() & num.isna(), rdwy + " & " + near)
addr = addr.mask(num.notna(), num + " " + rdwy)
massdot_df["address"] = addr.fillna("UNKNOWN") + " Somerville, MA"
massdot_df["address"] = massdot_df["address"].str.replace(r"^(\d+)\s+\1\s+", r"\1 ", regex=True)
road_text = (massdot_df[["RDWY", "NEAR_INT_RDWY", "MM_RTE", "EXIT_RTE"]]
             .fillna("").agg(" ".join, axis=1))
massdot_df["interstate"] = road_text.str.contains(r"\bI[- ]?\d{2,3}\b", case=False, regex=True)
massdot_df["interstate"] = massdot_df["interstate"].map({True: int(1), False: None})
massdot_df["latitude"] = massdot_df["LAT"].round(4)
massdot_df["longitude"] = massdot_df["LON"].round(4)

massdot_full_clean = massdot_df[["source","id","address","date","injuryseverity",
                                               "time","police","cyclists_involved",
                                               "pedestrians_involved","latitude","longitude","interstate"]]

massdot_full_clean = massdot_full_clean.dropna(subset=["latitude", "longitude"]).reset_index(drop=True)

massdot_nov2025 = massdot_full_clean[
    (pd.to_datetime(massdot_full_clean["date"]).dt.year == 2025) &
    (pd.to_datetime(massdot_full_clean["date"]).dt.month == 11)
]

massdot_nov2025.head(10)

,source,id,address,date,injuryseverity,time,police,cyclists_involved,pedestrians_involved,latitude,longitude,interstate
1134,MassDOT,5592693,"147 HAMPSHIRE ST Somerville, MA",2025-11-01,0,16:05:00,Local,1,0,42.3715,-71.0981,NaN
1154,MassDOT,5592563,"75 RICHDALE AVE Somerville, MA",2025-11-01,0,17:32:00,Local,0,0,42.3886,-71.1236,NaN
1161,MassDOT,5594949,"216 JACOBS STREET Somerville, MA",2025-11-06,0,19:20:00,Local,0,0,42.3722,-71.0747,NaN
1162,MassDOT,5594948,"BINNEY STREET & THIRD STREET Somerville, MA",2025-11-07,0,08:34:00,Local,0,0,42.3656,-71.0825,NaN
1163,MassDOT,5594947,"295 CONCORD AVENUE Somerville, MA",2025-11-06,0,15:15:00,Local,0,0,42.3837,-71.1338,NaN
1164,MassDOT,5594946,"2225 MASSACHUSETTS AVENUE Somerville, MA",2025-11-05,0,15:27:00,Local,0,0,42.3937,-71.1259,NaN
1165,MassDOT,5594945,"BRATTLE STREET & LAKEVIEW AVENUE Somerville, MA",2025-11-05,1,10:00:00,Local,0,0,42.3766,-71.1385,NaN
1166,MassDOT,5594944,"415 MAIN STREET Somerville, MA",2025-11-04,1,15:28:00,Local,0,0,42.3626,-71.0887,NaN
1167,MassDOT,5594943,"1280 MASSACHUSETTS AVE Somerville, MA",2025-11-07,0,23:03:00,Local,0,0,42.3728,-71.1169,NaN
1168,MassDOT,5594942,"2482 MASSACHUSETTS AVENUE Somerville, MA",2025-11-06,0,09:12:00,Local,0,0,42.3988,-71.1321,NaN

# De-duplication Functions

In [116]:
def within_100_meters(lat1, lon1, lat2, lon2):
    R = 6371000
    distance = 2 * R * np.arcsin(np.sqrt(np.sin((np.radians(lat2) - np.radians(lat1)) / 2) ** 2 + 
                np.cos(np.radians(lat1)) * np.cos(np.radians(lat2)) * np.sin((np.radians(lon2) - 
                np.radians(lon1)) / 2) ** 2))

    return distance <= 100

def within_6_hours(dt1, dt2):
    time_diff = abs(dt1 - dt2)
    return time_diff <= pd.Timedelta("6 hours")


def find_duplicates(df):
    df["datetime"] = pd.to_datetime(
        df["date"].astype("string") + " " + df["time"].astype("string"),
        errors="coerce"
    )

    df = df.sort_values("datetime").reset_index(drop=True)

    times = df["datetime"]

    crashes = df.to_dict(orient="records")

    duplicates = []

    for i in range(len(crashes)):
        j = i + 1
        while j < len(crashes) and within_6_hours(times[i], times[j]):
            if (
                crashes[i]["source"] != crashes[j]["source"]
                and within_100_meters(
                    crashes[i]["latitude"], crashes[i]["longitude"],
                    crashes[j]["latitude"], crashes[j]["longitude"]
                )
            ):
                duplicates.append((
                    crashes[i]["id"], crashes[j]["id"]
                ))
            j += 1

    if len(duplicates) == 0:
        return pd.DataFrame()

    pairs = pd.DataFrame(duplicates, columns=["id_1", "id_2"])

    cols = ["source", "id", "datetime", "address", "latitude", "longitude"]
    info = df[cols].drop_duplicates("id")

    out = (
        pairs
        .merge(info.add_suffix("_1"), on="id_1", how="left")
        .merge(info.add_suffix("_2"), on="id_2", how="left")
    )

    return out

# De-duplication on Somerville and MassDOT Data

In [119]:
duplicates_combined = find_duplicates(combined_nov2025)
print(f"{len(duplicates_combined)} potential duplicates found")
duplicates_combined

26 potential duplicates found

,id_1,id_2,source_1,datetime_1,address_1,latitude_1,longitude_1,source_2,datetime_2,address_2,latitude_2,longitude_2
0,5607854,25068117,MassDOT,2025-11-01 00:55:00,"72 PROFESSORS ROW Somerville, MA",42.4065,-71.1213,Somerville,2025-11-01 00:55:00,"72 PROFESSORS ROW Somerville, MA",42.4063,-71.1214
1,25068134,5607845,Somerville,2025-11-01 01:50:00,"243 POWDER HOUSE BLVD Somerville, MA",42.4074,-71.1297,MassDOT,2025-11-01 01:50:00,"243 POWDER HOUSE BLVD Somerville, MA",42.4072,-71.1298
2,5607853,25069235,MassDOT,2025-11-05 17:03:00,"HIGHLAND AV & WILLOW AV Somerville, MA",42.3941,-71.1168,Somerville,2025-11-05 17:03:00,"HIGHLAND AV & WILLOW AV Somerville, MA",42.3941,-71.1168
3,25069465,5607858,Somerville,2025-11-06 15:28:00,"101 WASHINGTON ST Somerville, MA",42.3814,-71.0863,MassDOT,2025-11-06 15:28:00,WASHINGTON STREET & FRANKLIN STREET Somerville...,42.3813,-71.0862
4,25069606,5607860,Somerville,2025-11-07 08:45:00,"212 HOLLAND ST Somerville, MA",42.4022,-71.1269,MassDOT,2025-11-07 08:45:00,"212 HOLLAND ST Somerville, MA",42.4022,-71.1267
5,25069834,5607872,Somerville,2025-11-08 02:10:00,"118 PROSPECT ST Somerville, MA",42.3745,-71.0969,MassDOT,2025-11-08 02:10:00,"118 PROSPECT ST Somerville, MA",42.3747,-71.0972
6,25069911,5607846,Somerville,2025-11-08 12:28:00,"BENTON RD & HIGHLAND AV Somerville, MA",42.3890,-71.1052,MassDOT,2025-11-08 12:28:00,"BENTON RD HIGHLAND AV Somerville, MA",42.3890,-71.1052
7,5607866,25070207,MassDOT,2025-11-09 18:08:00,"FOREST ST N & BEACON ST E Somerville, MA",42.3854,-71.1152,Somerville,2025-11-09 18:08:00,"FOREST ST & BEACON ST Somerville, MA",42.3854,-71.1152
8,25070652,5607862,Somerville,2025-11-11 14:01:00,"23 HAMLET ST Somerville, MA",42.3839,-71.0934,MassDOT,2025-11-11 14:01:00,"23 HAMLET ST Somerville, MA",42.3838,-71.0931
9,25070705,5607873,Somerville,2025-11-11 18:28:00,"IBBETSON ST & LOWELL ST Somerville, MA",42.3863,-71.1107,MassDOT,2025-11-11 18:28:00,"IBBETSON ST & LOWELL ST Somerville, MA",42.3863,-71.1107
10,25070716,5607905,Somerville,2025-11-11 19:53:00,"JEROME CT & SYCAMORE ST Somerville, MA",42.3896,-71.1007,MassDOT,2025-11-11 19:53:00,"JEROME CT SYCAMORE ST Somerville, MA",42.3895,-71.1007
11,25071093,5607867,Somerville,2025-11-13 10:20:00,"14 MCGRATH HWY Somerville, MA",42.3746,-71.0850,MassDOT,2025-11-13 10:20:00,"14 MCGRATH HWY Somerville, MA",42.3749,-71.0847
12,25071271,5607871,Somerville,2025-11-13 21:56:00,"262 SCHOOL ST Somerville, MA",42.3928,-71.0950,MassDOT,2025-11-13 21:56:00,"262 SCHOOL ST Somerville, MA",42.3927,-71.0948
13,25071400,5607856,Somerville,2025-11-14 11:55:00,"266 BROADWAY Somerville, MA",42.3908,-71.0912,MassDOT,2025-11-14 11:55:00,"266 BROADWAY Somerville, MA",42.3910,-71.0910
14,25072317,5607892,Somerville,2025-11-18 06:18:00,"BROADWAY & WARNER ST Somerville, MA",42.4012,-71.1164,MassDOT,2025-11-18 06:18:00,"BROADWAY W & WARNER ST N Somerville, MA",42.4012,-71.1171
15,25072494,5607870,Somerville,2025-11-18 18:13:00,"480 MYSTIC AV Somerville, MA",42.3962,-71.0905,MassDOT,2025-11-18 18:13:00,"480 MYSTIC AV Somerville, MA",42.3964,-71.0902
16,25072775,5607874,Somerville,2025-11-20 00:05:00,"CENTRAL ST & HIGHLAND AV Somerville, MA",42.3884,-71.1034,MassDOT,2025-11-20 00:05:00,"CENTRAL ST & HIGHLAND AV Somerville, MA",42.3884,-71.1034
17,25072981,5607883,Somerville,2025-11-20 18:26:00,"156 HIGHLAND AV Somerville, MA",42.3883,-71.1038,MassDOT,2025-11-20 18:26:00,"156 HIGHLAND AV Somerville, MA",42.3885,-71.1037
18,25073001,5607875,Somerville,2025-11-20 19:37:00,"COLLEGE AV & FRANCESCA AV Somerville, MA",42.3991,-71.1197,MassDOT,2025-11-20 19:37:00,"COLLEGE AV & FRANCESCA AV Somerville, MA",42.3991,-71.1198
19,5607864,25073498,MassDOT,2025-11-22 19:09:00,"19 ALBION ST Somerville, MA",42.3901,-71.1036,Somerville,2025-11-22 19:09:00,"19 ALBION ST Somerville, MA",42.3902,-71.1035
20,5607884,25073689,MassDOT,2025-11-23 19:18:00,"183 SCHOOL ST Somerville, MA",42.3896,-71.0969,Somerville,2025-11-23 19:18:00,"183 SCHOOL ST Somerville, MA",42.3895,-71.0966
21,5607878,25073928,MassDOT,2025-11-24 21:31:00,"CAMERON AV HOLLAND ST Somerville, MA",42.4010,-71.1261,Somerville,2025-11-24 21:31:00,"CAMERON AV & HOLLAND ST Somerville, MA",42.4010,-71.1261
22,25074321,5607879,Somerville,2025-11-26 17:06:00,"217 HIGHLAND AV Somerville, MA",42.3903,-71.1077,MassDOT,2025-11-26 17:06:00,"217 HIGHLAND AV Somerville, MA",42.3901,-71.1078
23,5607888,25074454,MassDOT,2025-11-27 10:51:00,"GLEN ST & PEARL ST Somerville, MA",42.3852,-71.0861,Somerville,2025-11-27 10:51:00,"GLEN ST & PEARL ST Somerville, MA",42.3851,-71.0861
24,5607868,25074818,MassDOT,2025-11-29 15:16:00,"WARREN AV & COLUMBUS AVE Somerville, MA",42.3817,-71.0949,Somerville,2025-11-29 15:16:00,"33 WARREN AV Somerville, MA",42.3815,-71.0949
25,5607876,25074854,MassDOT,2025-11-29 18:42:00,"BOW ST & WALNUT ST Somerville, MA",42.3810,-71.0972,Somerville,2025-11-29 18:42:00,"BOW ST & WALNUT ST Somerville, MA",42.3810,-71.0972